Repository w3c-fedid/digital-credentials, pull requests merged in 2025-06, with the labels that each got.

#248 s/user consent/user permission
  index.html
Labels: agenda+

#253 Add initial text for permission & transparency
  index.html
Labels: privacy-considerations

#260 Add initial privacy considerations section for protocol requirements
  index.html
Labels: privacy-considerations

#285 Clean up privacy considerations TODO sections
  index.html
Labels: privacy-considerations

#300 Chore: fix HTML Validator issues
  index.html
Labels: editorial

#283 Add initial privacy considerations for fingerprinting and data leakage
  index.html
Labels: privacy-considerations
